--liquibase formatted sql

--changeset vjs:1
CREATE TABLE notification_tasks
(
    id                     BIGINT generated by default as identity primary key,
    message                TEXT      NOT NULL,
    chat_id                BIGINT    NOT NULL,
    notification_date_time TIMESTAMP NOT NULL
);

--changeset vjs:2
-- ALTER TABLE notification_tasks rename COLUMN chat_id TO chatid;